# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Bob.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QMainWindow,
    QPushButton, QSizePolicy, QWidget)
from UEPicker.view import resource_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(450, 630)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"QPushButton:checked:!pressed    { border: 2px solid white}\n"
"QPushButton:hover {\n"
"    border-width: 4px;\n"
"    border-radius: 10px;\n"
"    border:2px solid white;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"}\n"
"#MainWindow {\n"
"background-color:rgb(36, 36, 36);\n"
"foreground-color:white;}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        self.select_all = QPushButton(self.centralwidget)
        self.select_all.setObjectName(u"select_all")
        self.select_all.setGeometry(QRect(40, 600, 370, 20))
        self.select_all.setStyleSheet(u"color: rgb(200, 200, 200);\n"
"background-color: rgb(50, 50, 50);")
        self.select_all.setCheckable(True)
        self.hand_L_ring03_ctrl = QPushButton(self.centralwidget)
        self.hand_L_ring03_ctrl.setObjectName(u"hand_L_ring03_ctrl")
        self.hand_L_ring03_ctrl.setGeometry(QRect(370, 360, 20, 20))
        self.hand_L_ring03_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_ring03_ctrl.setCheckable(True)
        self.clavicle_R_clavicle_ctrl = QPushButton(self.centralwidget)
        self.clavicle_R_clavicle_ctrl.setObjectName(u"clavicle_R_clavicle_ctrl")
        self.clavicle_R_clavicle_ctrl.setGeometry(QRect(180, 110, 45, 20))
        self.clavicle_R_clavicle_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.clavicle_R_clavicle_ctrl.setCheckable(True)
        self.hand_L_ring01_ctrl = QPushButton(self.centralwidget)
        self.hand_L_ring01_ctrl.setObjectName(u"hand_L_ring01_ctrl")
        self.hand_L_ring01_ctrl.setGeometry(QRect(370, 290, 20, 40))
        self.hand_L_ring01_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_ring01_ctrl.setCheckable(True)
        self.spine_M_cog_ctrl = QPushButton(self.centralwidget)
        self.spine_M_cog_ctrl.setObjectName(u"spine_M_cog_ctrl")
        self.spine_M_cog_ctrl.setGeometry(QRect(180, 290, 90, 20))
        self.spine_M_cog_ctrl.setStyleSheet(u"background-color: rgb(255, 170, 127);")
        self.spine_M_cog_ctrl.setCheckable(True)
        self.mainSrt_M_Offset_ctrl = QPushButton(self.centralwidget)
        self.mainSrt_M_Offset_ctrl.setObjectName(u"mainSrt_M_Offset_ctrl")
        self.mainSrt_M_Offset_ctrl.setGeometry(QRect(40, 580, 370, 20))
        self.mainSrt_M_Offset_ctrl.setStyleSheet(u"background-color: rgb(255, 170, 127);")
        self.mainSrt_M_Offset_ctrl.setCheckable(True)
        self.leg_L_shinFK_ctrl = QPushButton(self.centralwidget)
        self.leg_L_shinFK_ctrl.setObjectName(u"leg_L_shinFK_ctrl")
        self.leg_L_shinFK_ctrl.setGeometry(QRect(230, 440, 40, 90))
        self.leg_L_shinFK_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.leg_L_shinFK_ctrl.setCheckable(True)
        self.hand_L_middle02_ctrl = QPushButton(self.centralwidget)
        self.hand_L_middle02_ctrl.setObjectName(u"hand_L_middle02_ctrl")
        self.hand_L_middle02_ctrl.setGeometry(QRect(350, 330, 20, 30))
        self.hand_L_middle02_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_middle02_ctrl.setCheckable(True)
        self.hand_L_middle03_ctrl = QPushButton(self.centralwidget)
        self.hand_L_middle03_ctrl.setObjectName(u"hand_L_middle03_ctrl")
        self.hand_L_middle03_ctrl.setGeometry(QRect(350, 360, 20, 20))
        self.hand_L_middle03_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_middle03_ctrl.setCheckable(True)
        self.hand_L_pinky02_ctrl = QPushButton(self.centralwidget)
        self.hand_L_pinky02_ctrl.setObjectName(u"hand_L_pinky02_ctrl")
        self.hand_L_pinky02_ctrl.setGeometry(QRect(390, 330, 20, 30))
        self.hand_L_pinky02_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_pinky02_ctrl.setCheckable(True)
        self.spine_M_spine04_ctrl = QPushButton(self.centralwidget)
        self.spine_M_spine04_ctrl.setObjectName(u"spine_M_spine04_ctrl")
        self.spine_M_spine04_ctrl.setGeometry(QRect(180, 130, 90, 20))
        self.spine_M_spine04_ctrl.setStyleSheet(u"background-color: rgb(240, 200, 40);")
        self.spine_M_spine04_ctrl.setCheckable(True)
        self.hand_L_pinky03_ctrl = QPushButton(self.centralwidget)
        self.hand_L_pinky03_ctrl.setObjectName(u"hand_L_pinky03_ctrl")
        self.hand_L_pinky03_ctrl.setGeometry(QRect(390, 360, 20, 20))
        self.hand_L_pinky03_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_pinky03_ctrl.setCheckable(True)
        self.hand_L_index02_ctrl = QPushButton(self.centralwidget)
        self.hand_L_index02_ctrl.setObjectName(u"hand_L_index02_ctrl")
        self.hand_L_index02_ctrl.setGeometry(QRect(330, 330, 20, 30))
        self.hand_L_index02_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_index02_ctrl.setCheckable(True)
        self.hand_L_pinky01_ctrl = QPushButton(self.centralwidget)
        self.hand_L_pinky01_ctrl.setObjectName(u"hand_L_pinky01_ctrl")
        self.hand_L_pinky01_ctrl.setGeometry(QRect(390, 290, 20, 40))
        self.hand_L_pinky01_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_pinky01_ctrl.setCheckable(True)
        self.hand_L_ring02_ctrl = QPushButton(self.centralwidget)
        self.hand_L_ring02_ctrl.setObjectName(u"hand_L_ring02_ctrl")
        self.hand_L_ring02_ctrl.setGeometry(QRect(370, 330, 20, 30))
        self.hand_L_ring02_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_ring02_ctrl.setCheckable(True)
        self.arm_L_IK_ctrl = QPushButton(self.centralwidget)
        self.arm_L_IK_ctrl.setObjectName(u"arm_L_IK_ctrl")
        self.arm_L_IK_ctrl.setGeometry(QRect(330, 230, 80, 30))
        self.arm_L_IK_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.arm_L_IK_ctrl.setCheckable(True)
        self.hand_L_index01_ctrl = QPushButton(self.centralwidget)
        self.hand_L_index01_ctrl.setObjectName(u"hand_L_index01_ctrl")
        self.hand_L_index01_ctrl.setGeometry(QRect(330, 290, 20, 40))
        self.hand_L_index01_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_index01_ctrl.setCheckable(True)
        self.foot_L_ankleFK_ctrl = QPushButton(self.centralwidget)
        self.foot_L_ankleFK_ctrl.setObjectName(u"foot_L_ankleFK_ctrl")
        self.foot_L_ankleFK_ctrl.setGeometry(QRect(270, 530, 60, 40))
        self.foot_L_ankleFK_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.foot_L_ankleFK_ctrl.setCheckable(True)
        self.spine_M_spine01_ctrl = QPushButton(self.centralwidget)
        self.spine_M_spine01_ctrl.setObjectName(u"spine_M_spine01_ctrl")
        self.spine_M_spine01_ctrl.setGeometry(QRect(180, 250, 90, 20))
        self.spine_M_spine01_ctrl.setStyleSheet(u"background-color: rgb(240, 200, 40);")
        self.spine_M_spine01_ctrl.setCheckable(True)
        self.leg_L_femurFK_ctrl = QPushButton(self.centralwidget)
        self.leg_L_femurFK_ctrl.setObjectName(u"leg_L_femurFK_ctrl")
        self.leg_L_femurFK_ctrl.setGeometry(QRect(230, 310, 40, 90))
        self.leg_L_femurFK_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.leg_L_femurFK_ctrl.setCheckable(True)
        self.neck_M_neck01_ctrl = QPushButton(self.centralwidget)
        self.neck_M_neck01_ctrl.setObjectName(u"neck_M_neck01_ctrl")
        self.neck_M_neck01_ctrl.setGeometry(QRect(210, 90, 30, 20))
        self.neck_M_neck01_ctrl.setStyleSheet(u"background-color: rgb(240, 200, 40);")
        self.neck_M_neck01_ctrl.setCheckable(True)
        self.foot_L_toeFK_ctrl = QPushButton(self.centralwidget)
        self.foot_L_toeFK_ctrl.setObjectName(u"foot_L_toeFK_ctrl")
        self.foot_L_toeFK_ctrl.setGeometry(QRect(330, 530, 40, 40))
        self.foot_L_toeFK_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.foot_L_toeFK_ctrl.setCheckable(True)
        self.head_M_head_ctrl = QPushButton(self.centralwidget)
        self.head_M_head_ctrl.setObjectName(u"head_M_head_ctrl")
        self.head_M_head_ctrl.setGeometry(QRect(190, 10, 70, 61))
        self.head_M_head_ctrl.setAutoFillBackground(False)
        self.head_M_head_ctrl.setStyleSheet(u"background-color: rgb(240, 200, 40);\n"
"background-image: url(:/rsc/smile.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.head_M_head_ctrl.setCheckable(True)
        self.head_M_head_ctrl.setFlat(False)
        self.thumb_02_l_ctrl = QPushButton(self.centralwidget)
        self.thumb_02_l_ctrl.setObjectName(u"thumb_02_l_ctrl")
        self.thumb_02_l_ctrl.setGeometry(QRect(310, 280, 20, 30))
        self.thumb_02_l_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.thumb_02_l_ctrl.setCheckable(True)
        self.spine_M_spine03_ctrl = QPushButton(self.centralwidget)
        self.spine_M_spine03_ctrl.setObjectName(u"spine_M_spine03_ctrl")
        self.spine_M_spine03_ctrl.setGeometry(QRect(180, 150, 90, 60))
        self.spine_M_spine03_ctrl.setStyleSheet(u"background-color: rgb(170, 25, 25);")
        self.spine_M_spine03_ctrl.setCheckable(True)
        self.arm_L_UpV_ctrl = QPushButton(self.centralwidget)
        self.arm_L_UpV_ctrl.setObjectName(u"arm_L_UpV_ctrl")
        self.arm_L_UpV_ctrl.setGeometry(QRect(350, 110, 40, 40))
        self.arm_L_UpV_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.arm_L_UpV_ctrl.setCheckable(True)
        self.arm_L_bicepFK_ctrl = QPushButton(self.centralwidget)
        self.arm_L_bicepFK_ctrl.setObjectName(u"arm_L_bicepFK_ctrl")
        self.arm_L_bicepFK_ctrl.setGeometry(QRect(270, 110, 80, 40))
        self.arm_L_bicepFK_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.arm_L_bicepFK_ctrl.setCheckable(True)
        self.leg_L_UpV_ctrl = QPushButton(self.centralwidget)
        self.leg_L_UpV_ctrl.setObjectName(u"leg_L_UpV_ctrl")
        self.leg_L_UpV_ctrl.setGeometry(QRect(230, 400, 40, 40))
        self.leg_L_UpV_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.leg_L_UpV_ctrl.setCheckable(True)
        self.hand_L_hand_ctrl = QPushButton(self.centralwidget)
        self.hand_L_hand_ctrl.setObjectName(u"hand_L_hand_ctrl")
        self.hand_L_hand_ctrl.setGeometry(QRect(330, 260, 80, 30))
        self.hand_L_hand_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_hand_ctrl.setCheckable(True)
        self.clavicle_L_clavicle_ctrl = QPushButton(self.centralwidget)
        self.clavicle_L_clavicle_ctrl.setObjectName(u"clavicle_L_clavicle_ctrl")
        self.clavicle_L_clavicle_ctrl.setGeometry(QRect(225, 110, 45, 20))
        self.clavicle_L_clavicle_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.clavicle_L_clavicle_ctrl.setCheckable(True)
        self.hand_L_index03_ctrl = QPushButton(self.centralwidget)
        self.hand_L_index03_ctrl.setObjectName(u"hand_L_index03_ctrl")
        self.hand_L_index03_ctrl.setGeometry(QRect(330, 360, 20, 20))
        self.hand_L_index03_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_index03_ctrl.setCheckable(True)
        self.spine_M_spine02_ctrl = QPushButton(self.centralwidget)
        self.spine_M_spine02_ctrl.setObjectName(u"spine_M_spine02_ctrl")
        self.spine_M_spine02_ctrl.setGeometry(QRect(180, 210, 90, 41))
        self.spine_M_spine02_ctrl.setStyleSheet(u"background-color: rgb(170, 25, 25);")
        self.spine_M_spine02_ctrl.setCheckable(True)
        self.arm_L_forearmFK_ctrl = QPushButton(self.centralwidget)
        self.arm_L_forearmFK_ctrl.setObjectName(u"arm_L_forearmFK_ctrl")
        self.arm_L_forearmFK_ctrl.setGeometry(QRect(350, 149, 40, 81))
        self.arm_L_forearmFK_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.arm_L_forearmFK_ctrl.setCheckable(True)
        self.thumb_03_l_ctrl = QPushButton(self.centralwidget)
        self.thumb_03_l_ctrl.setObjectName(u"thumb_03_l_ctrl")
        self.thumb_03_l_ctrl.setGeometry(QRect(310, 310, 20, 30))
        self.thumb_03_l_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.thumb_03_l_ctrl.setCheckable(True)
        self.hand_L_middle01_ctrl = QPushButton(self.centralwidget)
        self.hand_L_middle01_ctrl.setObjectName(u"hand_L_middle01_ctrl")
        self.hand_L_middle01_ctrl.setGeometry(QRect(350, 290, 20, 40))
        self.hand_L_middle01_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.hand_L_middle01_ctrl.setCheckable(True)
        self.leg_L_IK_ctrl = QPushButton(self.centralwidget)
        self.leg_L_IK_ctrl.setObjectName(u"leg_L_IK_ctrl")
        self.leg_L_IK_ctrl.setGeometry(QRect(230, 530, 40, 40))
        self.leg_L_IK_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.leg_L_IK_ctrl.setCheckable(True)
        self.thumb_01_l_ctrl = QPushButton(self.centralwidget)
        self.thumb_01_l_ctrl.setObjectName(u"thumb_01_l_ctrl")
        self.thumb_01_l_ctrl.setGeometry(QRect(310, 230, 20, 50))
        self.thumb_01_l_ctrl.setStyleSheet(u"background-color: rgb(60, 60, 135);\n"
"color: rgb(255, 255, 255);")
        self.thumb_01_l_ctrl.setCheckable(True)
        self.neck_M_neck02_ctrl = QPushButton(self.centralwidget)
        self.neck_M_neck02_ctrl.setObjectName(u"neck_M_neck02_ctrl")
        self.neck_M_neck02_ctrl.setGeometry(QRect(210, 70, 30, 20))
        self.neck_M_neck02_ctrl.setStyleSheet(u"background-color: rgb(240, 200, 40);")
        self.neck_M_neck02_ctrl.setCheckable(True)
        self.spine_M_pelvis_ctrl = QPushButton(self.centralwidget)
        self.spine_M_pelvis_ctrl.setObjectName(u"spine_M_pelvis_ctrl")
        self.spine_M_pelvis_ctrl.setGeometry(QRect(180, 270, 90, 20))
        self.spine_M_pelvis_ctrl.setStyleSheet(u"background-color: rgb(155, 15, 5);")
        self.spine_M_pelvis_ctrl.setCheckable(True)
        self.foot_L_ankleIK_ctrl = QPushButton(self.centralwidget)
        self.foot_L_ankleIK_ctrl.setObjectName(u"foot_L_ankleIK_ctrl")
        self.foot_L_ankleIK_ctrl.setGeometry(QRect(290, 500, 21, 21))
        self.foot_L_ankleIK_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.foot_L_ankleIK_ctrl.setCheckable(True)
        self.foot_L_toeIK_ctrl = QPushButton(self.centralwidget)
        self.foot_L_toeIK_ctrl.setObjectName(u"foot_L_toeIK_ctrl")
        self.foot_L_toeIK_ctrl.setGeometry(QRect(340, 500, 21, 21))
        self.foot_L_toeIK_ctrl.setStyleSheet(u"background-color: rgb(32, 32, 107);\n"
"color: rgb(218, 218, 218);")
        self.foot_L_toeIK_ctrl.setCheckable(True)
        self.arm_R_bicepFK_ctrl = QPushButton(self.centralwidget)
        self.arm_R_bicepFK_ctrl.setObjectName(u"arm_R_bicepFK_ctrl")
        self.arm_R_bicepFK_ctrl.setGeometry(QRect(100, 110, 80, 40))
        self.arm_R_bicepFK_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.arm_R_bicepFK_ctrl.setCheckable(True)
        self.arm_R_UpV_ctrl = QPushButton(self.centralwidget)
        self.arm_R_UpV_ctrl.setObjectName(u"arm_R_UpV_ctrl")
        self.arm_R_UpV_ctrl.setGeometry(QRect(60, 110, 40, 40))
        self.arm_R_UpV_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.arm_R_UpV_ctrl.setCheckable(True)
        self.arm_R_forearmFK_ctrl = QPushButton(self.centralwidget)
        self.arm_R_forearmFK_ctrl.setObjectName(u"arm_R_forearmFK_ctrl")
        self.arm_R_forearmFK_ctrl.setGeometry(QRect(60, 150, 40, 81))
        self.arm_R_forearmFK_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.arm_R_forearmFK_ctrl.setCheckable(True)
        self.arm_R_IK_ctrl = QPushButton(self.centralwidget)
        self.arm_R_IK_ctrl.setObjectName(u"arm_R_IK_ctrl")
        self.arm_R_IK_ctrl.setGeometry(QRect(40, 230, 80, 30))
        self.arm_R_IK_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.arm_R_IK_ctrl.setCheckable(True)
        self.hand_R_hand_ctrl = QPushButton(self.centralwidget)
        self.hand_R_hand_ctrl.setObjectName(u"hand_R_hand_ctrl")
        self.hand_R_hand_ctrl.setGeometry(QRect(40, 260, 80, 30))
        self.hand_R_hand_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_hand_ctrl.setCheckable(True)
        self.hand_R_pinky02_ctrl = QPushButton(self.centralwidget)
        self.hand_R_pinky02_ctrl.setObjectName(u"hand_R_pinky02_ctrl")
        self.hand_R_pinky02_ctrl.setGeometry(QRect(40, 330, 20, 30))
        self.hand_R_pinky02_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_pinky02_ctrl.setCheckable(True)
        self.hand_R_pinky01_ctrl = QPushButton(self.centralwidget)
        self.hand_R_pinky01_ctrl.setObjectName(u"hand_R_pinky01_ctrl")
        self.hand_R_pinky01_ctrl.setGeometry(QRect(40, 290, 20, 40))
        self.hand_R_pinky01_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_pinky01_ctrl.setCheckable(True)
        self.hand_R_pinky03_ctrl = QPushButton(self.centralwidget)
        self.hand_R_pinky03_ctrl.setObjectName(u"hand_R_pinky03_ctrl")
        self.hand_R_pinky03_ctrl.setGeometry(QRect(40, 360, 20, 20))
        self.hand_R_pinky03_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_pinky03_ctrl.setCheckable(True)
        self.hand_R_ring02_ctrl = QPushButton(self.centralwidget)
        self.hand_R_ring02_ctrl.setObjectName(u"hand_R_ring02_ctrl")
        self.hand_R_ring02_ctrl.setGeometry(QRect(60, 330, 20, 30))
        self.hand_R_ring02_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_ring02_ctrl.setCheckable(True)
        self.hand_R_ring03_ctrl = QPushButton(self.centralwidget)
        self.hand_R_ring03_ctrl.setObjectName(u"hand_R_ring03_ctrl")
        self.hand_R_ring03_ctrl.setGeometry(QRect(60, 360, 20, 20))
        self.hand_R_ring03_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_ring03_ctrl.setCheckable(True)
        self.hand_R_ring01_ctrl = QPushButton(self.centralwidget)
        self.hand_R_ring01_ctrl.setObjectName(u"hand_R_ring01_ctrl")
        self.hand_R_ring01_ctrl.setGeometry(QRect(60, 290, 20, 40))
        self.hand_R_ring01_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_ring01_ctrl.setCheckable(True)
        self.hand_R_middle01_ctrl = QPushButton(self.centralwidget)
        self.hand_R_middle01_ctrl.setObjectName(u"hand_R_middle01_ctrl")
        self.hand_R_middle01_ctrl.setGeometry(QRect(80, 290, 20, 40))
        self.hand_R_middle01_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_middle01_ctrl.setCheckable(True)
        self.hand_R_middle03_ctrl = QPushButton(self.centralwidget)
        self.hand_R_middle03_ctrl.setObjectName(u"hand_R_middle03_ctrl")
        self.hand_R_middle03_ctrl.setGeometry(QRect(80, 360, 20, 20))
        self.hand_R_middle03_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_middle03_ctrl.setCheckable(True)
        self.hand_R_middle02_ctrl = QPushButton(self.centralwidget)
        self.hand_R_middle02_ctrl.setObjectName(u"hand_R_middle02_ctrl")
        self.hand_R_middle02_ctrl.setGeometry(QRect(80, 330, 20, 30))
        self.hand_R_middle02_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_middle02_ctrl.setCheckable(True)
        self.hand_R_index02_ctrl = QPushButton(self.centralwidget)
        self.hand_R_index02_ctrl.setObjectName(u"hand_R_index02_ctrl")
        self.hand_R_index02_ctrl.setGeometry(QRect(100, 330, 20, 30))
        self.hand_R_index02_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_index02_ctrl.setCheckable(True)
        self.hand_R_index01_ctrl = QPushButton(self.centralwidget)
        self.hand_R_index01_ctrl.setObjectName(u"hand_R_index01_ctrl")
        self.hand_R_index01_ctrl.setGeometry(QRect(100, 290, 20, 40))
        self.hand_R_index01_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_index01_ctrl.setCheckable(True)
        self.hand_R_index03_ctrl = QPushButton(self.centralwidget)
        self.hand_R_index03_ctrl.setObjectName(u"hand_R_index03_ctrl")
        self.hand_R_index03_ctrl.setGeometry(QRect(100, 360, 20, 20))
        self.hand_R_index03_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.hand_R_index03_ctrl.setCheckable(True)
        self.thumb_01_r_ctrl = QPushButton(self.centralwidget)
        self.thumb_01_r_ctrl.setObjectName(u"thumb_01_r_ctrl")
        self.thumb_01_r_ctrl.setGeometry(QRect(120, 230, 20, 50))
        self.thumb_01_r_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.thumb_01_r_ctrl.setCheckable(True)
        self.thumb_02_r_ctrl = QPushButton(self.centralwidget)
        self.thumb_02_r_ctrl.setObjectName(u"thumb_02_r_ctrl")
        self.thumb_02_r_ctrl.setGeometry(QRect(120, 280, 20, 30))
        self.thumb_02_r_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.thumb_02_r_ctrl.setCheckable(True)
        self.thumb_03_r_ctrl = QPushButton(self.centralwidget)
        self.thumb_03_r_ctrl.setObjectName(u"thumb_03_r_ctrl")
        self.thumb_03_r_ctrl.setGeometry(QRect(120, 310, 20, 30))
        self.thumb_03_r_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.thumb_03_r_ctrl.setCheckable(True)
        self.leg_R_shinFK_ctrl = QPushButton(self.centralwidget)
        self.leg_R_shinFK_ctrl.setObjectName(u"leg_R_shinFK_ctrl")
        self.leg_R_shinFK_ctrl.setGeometry(QRect(180, 440, 40, 90))
        self.leg_R_shinFK_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.leg_R_shinFK_ctrl.setCheckable(True)
        self.leg_R_UpV_ctrl = QPushButton(self.centralwidget)
        self.leg_R_UpV_ctrl.setObjectName(u"leg_R_UpV_ctrl")
        self.leg_R_UpV_ctrl.setGeometry(QRect(180, 400, 40, 40))
        self.leg_R_UpV_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.leg_R_UpV_ctrl.setCheckable(True)
        self.leg_R_femurFK_ctrl = QPushButton(self.centralwidget)
        self.leg_R_femurFK_ctrl.setObjectName(u"leg_R_femurFK_ctrl")
        self.leg_R_femurFK_ctrl.setGeometry(QRect(180, 310, 40, 90))
        self.leg_R_femurFK_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.leg_R_femurFK_ctrl.setCheckable(True)
        self.leg_R_IK_ctrl = QPushButton(self.centralwidget)
        self.leg_R_IK_ctrl.setObjectName(u"leg_R_IK_ctrl")
        self.leg_R_IK_ctrl.setGeometry(QRect(180, 530, 40, 40))
        self.leg_R_IK_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.leg_R_IK_ctrl.setCheckable(True)
        self.foot_R_ankleFK_ctrl = QPushButton(self.centralwidget)
        self.foot_R_ankleFK_ctrl.setObjectName(u"foot_R_ankleFK_ctrl")
        self.foot_R_ankleFK_ctrl.setGeometry(QRect(120, 530, 60, 40))
        self.foot_R_ankleFK_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.foot_R_ankleFK_ctrl.setCheckable(True)
        self.foot_R_toeFK_ctrl = QPushButton(self.centralwidget)
        self.foot_R_toeFK_ctrl.setObjectName(u"foot_R_toeFK_ctrl")
        self.foot_R_toeFK_ctrl.setGeometry(QRect(80, 530, 40, 40))
        self.foot_R_toeFK_ctrl.setStyleSheet(u"background-color: rgb(235, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.foot_R_toeFK_ctrl.setCheckable(True)
        self.foot_R_ankleIK_ctrl = QPushButton(self.centralwidget)
        self.foot_R_ankleIK_ctrl.setObjectName(u"foot_R_ankleIK_ctrl")
        self.foot_R_ankleIK_ctrl.setGeometry(QRect(140, 500, 21, 21))
        self.foot_R_ankleIK_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.foot_R_ankleIK_ctrl.setCheckable(True)
        self.foot_R_toeIK_ctrl = QPushButton(self.centralwidget)
        self.foot_R_toeIK_ctrl.setObjectName(u"foot_R_toeIK_ctrl")
        self.foot_R_toeIK_ctrl.setGeometry(QRect(90, 500, 21, 21))
        self.foot_R_toeIK_ctrl.setStyleSheet(u"background-color: rgb(180, 48, 48);\n"
"color: rgb(220, 220, 220);")
        self.foot_R_toeIK_ctrl.setCheckable(True)
        self.head_M_jaw_ctrl = QPushButton(self.centralwidget)
        self.head_M_jaw_ctrl.setObjectName(u"head_M_jaw_ctrl")
        self.head_M_jaw_ctrl.setGeometry(QRect(160, 50, 20, 20))
        self.head_M_jaw_ctrl.setStyleSheet(u"background-color: rgb(170, 25, 25);")
        self.head_M_jaw_ctrl.setCheckable(True)
        self.head_M_lookAt_ctrl = QPushButton(self.centralwidget)
        self.head_M_lookAt_ctrl.setObjectName(u"head_M_lookAt_ctrl")
        self.head_M_lookAt_ctrl.setGeometry(QRect(160, 20, 20, 20))
        self.head_M_lookAt_ctrl.setStyleSheet(u"background-color: rgb(170, 25, 25);")
        self.head_M_lookAt_ctrl.setCheckable(True)
        self.Reset_SRT = QGroupBox(self.centralwidget)
        self.Reset_SRT.setObjectName(u"Reset_SRT")
        self.Reset_SRT.setGeometry(QRect(330, 10, 111, 51))
        self.Reset_SRT.setStyleSheet(u"QPushButton:hover { border: 2px solid red}\n"
"QPushButton:pressed { border:10px solid  black}\n"
"#Reset_SRT{background-color: grey;foreground-color: white;}")
        self.Reset_SRT.setFlat(False)
        self.reset_s = QPushButton(self.Reset_SRT)
        self.reset_s.setObjectName(u"reset_s")
        self.reset_s.setGeometry(QRect(10, 20, 16, 16))
        self.reset_s.setStyleSheet(u"background-color: rgb(0, 200, 200);color:black")
        self.reset_s.setCheckable(False)
        self.reset_r = QPushButton(self.Reset_SRT)
        self.reset_r.setObjectName(u"reset_r")
        self.reset_r.setGeometry(QRect(30, 20, 16, 16))
        self.reset_r.setStyleSheet(u"background-color: rgb(0, 200, 200);color:black")
        self.reset_r.setCheckable(False)
        self.reset_t = QPushButton(self.Reset_SRT)
        self.reset_t.setObjectName(u"reset_t")
        self.reset_t.setGeometry(QRect(50, 20, 16, 16))
        self.reset_t.setStyleSheet(u"background-color: rgb(0, 200, 200);color:black")
        self.reset_t.setCheckable(False)
        self.reset_all = QPushButton(self.Reset_SRT)
        self.reset_all.setObjectName(u"reset_all")
        self.reset_all.setGeometry(QRect(70, 20, 31, 16))
        self.reset_all.setStyleSheet(u"background-color: rgb(0, 200, 200);color:black")
        self.reset_all.setCheckable(False)
        self.ctrlRigNames_cbx = QComboBox(self.centralwidget)
        self.ctrlRigNames_cbx.setObjectName(u"ctrlRigNames_cbx")
        self.ctrlRigNames_cbx.setGeometry(QRect(10, 10, 101, 21))
        self.refresh_btn = QPushButton(self.centralwidget)
        self.refresh_btn.setObjectName(u"refresh_btn")
        self.refresh_btn.setGeometry(QRect(120, 10, 21, 20))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CharacterPicker", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Select keys:</p><p>&quot;replace&quot;: 0</p><p>&quot;toggle&quot;: shift</p><p>&quot;deselect&quot;: ctrl</p><p>&quot;add&quot;: ctrl + shift</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.select_all.setText(QCoreApplication.translate("MainWindow", u"SELECT ALL", None))
        self.arm_L_IK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.head_M_head_ctrl.setText("")
        self.arm_L_UpV_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.leg_L_UpV_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.leg_L_IK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.foot_L_ankleIK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.foot_L_toeIK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.arm_R_UpV_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.arm_R_IK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.leg_R_UpV_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.leg_R_IK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.foot_R_ankleIK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.foot_R_toeIK_ctrl.setText(QCoreApplication.translate("MainWindow", u"IK", None))
        self.Reset_SRT.setTitle(QCoreApplication.translate("MainWindow", u"Reset_SRT", None))
        self.reset_s.setText(QCoreApplication.translate("MainWindow", u"S", None))
        self.reset_r.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.reset_t.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.reset_all.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.refresh_btn.setText(QCoreApplication.translate("MainWindow", u"R", None))
    # retranslateUi

